# Generated by Django 4.1 on 2022-11-09 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_product', '0009_remove_product_productor_product_image_and_more'),
        ('_deal', '0002_alter_deal_product_alter_deal_user_cons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.product'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user_cons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to=settings.AUTH_USER_MODEL),
        ),
    ]
