# Generated by Django 4.1 on 2022-11-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0008_alter_product_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productor',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(1, '직거래만'), (2, '택배거래만'), (3, '택배/직거래')], max_length=20),
        )
    ]
