# Generated by Django 4.1 on 2022-11-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0009_remove_product_image_representative_and_more'),
        ('_product', '0009_remove_product_productor_product_image_and_more'),
    ]

    operations = [
    ]
