# Generated by Django 4.1 on 2022-11-09 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_chatting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prod', to=settings.AUTH_USER_MODEL),
        ),
    ]
