# Generated by Django 4.1 on 2022-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/img/account_default.png', null=True, upload_to='profile'),
        ),
    ]
